name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "bff0c504-13b0-4106-824d-c878d55dfa59"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "d790701729a14feeaa94c3d120e869a0"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "e5bdcbc1a5e21d5f03100fae02fbbdcc_notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
